# Numpy

### Array
A data structure that is homogenous i.e stores same type of data. This is where it is different from a list

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]
arr = np.array(my_list)
print(type(arr),'\n',arr)

<class 'numpy.ndarray'> 
 [1 2 3 4 5]


In [3]:
print(arr.shape) # check dimensions of an array

(5,)


In [8]:
list1 = [1,2,3,2,1]
list2 = [3,4,5,6,7]
list3 = [0,1,1,1,0]
arr2 = np.array([list1,list2,list3])
print(arr2.shape)
print(arr2)
print(arr2.reshape(5,3)) # reshapes the array based on parameters provided

(3, 5)
[[1 2 3 2 1]
 [3 4 5 6 7]
 [0 1 1 1 0]]
[[1 2 3]
 [2 1 3]
 [4 5 6]
 [7 0 1]
 [1 1 0]]


In [12]:
# Indexing
print(arr[3]) # returns the fourth element of the array
print(arr2[:,:]) # the comma inside [] separates the rows and columns 
print(arr2[0:2,2:4]) # selects the rows 0,1(0:2) and columns 2,3(2:4)
print(arr2[2:,2:4])
print(arr2[1,1:4])


4
[[1 2 3 2 1]
 [3 4 5 6 7]
 [0 1 1 1 0]]
[[3 2]
 [5 6]]
[[1 1]]
[4 5 6]


In [13]:
# Functions for an array
arr3 = np.arange(0,15,step=3) # creates an array from 0 to 14 with steps=3;steps is optional
print(arr3)
arr4 = np.linspace(1,10,25) # creates an array from 1 to 10 with 25 digits equidistant from each other
print(arr4)

[ 0  3  6  9 12]
[ 1.     1.375  1.75   2.125  2.5    2.875  3.25   3.625  4.     4.375
  4.75   5.125  5.5    5.875  6.25   6.625  7.     7.375  7.75   8.125
  8.5    8.875  9.25   9.625 10.   ]


In [16]:
# copy and broadcast
org_arr = np.arange(0,10)
print("org_arr - ",org_arr)
copy_arr = org_arr
copy_arr[4:] = 100
print("copy_arr - ",copy_arr)
print("org_arr - ",org_arr)
# Arrays are reference types i.e when we assign the array to a variable or passing it to a function, a reference to the array is being
# passed and not a copy of itself. This is done because it is more memory efficient
copy_arr2 = org_arr.copy() # this passes a copy of the array and not the reference
print('copy_arr2 - ',copy_arr2)
copy_arr2[4:] = 50
print("org_arr - ",org_arr)
print("copy_arr2 - ", copy_arr2)

org_arr -  [0 1 2 3 4 5 6 7 8 9]
copy_arr -  [  0   1   2   3 100 100 100 100 100 100]
org_arr -  [  0   1   2   3 100 100 100 100 100 100]
copy_arr2 -  [  0   1   2   3 100 100 100 100 100 100]
org_arr -  [  0   1   2   3 100 100 100 100 100 100]
copy_arr2 -  [ 0  1  2  3 50 50 50 50 50 50]


In [27]:
# Array operations
arr_new = np.arange(1,11)
print("arr_new - ",arr_new)
print("Checking values less than 3 - ",arr_new<3)
print("Printing only less than 5 values - ",arr_new[arr_new<5])
print("Multiplying each element by 3 - ",arr_new*3) # This is different than list. In a list the number of elements increases by 3 times
print("Multiplication in a list - ",[1,2,3,4,5]*2)
print("creates an array with only 1s of length 6",np.ones(6, dtype=int)) #dtype is optional, default is float
print("Creates a 2D array with 1s of float type - \n",np.ones((3,4),dtype=float))

arr_new -  [ 1  2  3  4  5  6  7  8  9 10]
Checking values less than 3 -  [ True  True False False False False False False False False]
Printing only less than 5 values -  [1 2 3 4]
Multiplying each element by 3 -  [ 3  6  9 12 15 18 21 24 27 30]
Multiplication in a list -  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
creates an array with only 1s of length 6 [1 1 1 1 1 1]
Creates a 2D array with 1s of float type - 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [33]:
# Random distribution
print(np.random.rand(3,3)) #Returns random values of the given shape between values 0 and 1
print(np.random.randn(4,4)) #Returns an array with values in random distribution
print(np.random.randint(0,10,8)) # returns an array of size 8 with values b/w 0 and 100
print(np.random.randint(0,10,8).reshape(4,2)) # reshapes the array returned above in a 4x2 array
print(np.random.random_sample((2,3))) # Returns an array of size 2x3 with random float values

[[0.60553157 0.82224659 0.47918131]
 [0.07841325 0.94214785 0.29197856]
 [0.89335452 0.4071153  0.05891234]]
[[-0.99349247  1.6260104  -1.51630451  1.63954888]
 [-0.30553364  0.64295524 -0.86372012 -1.36892808]
 [ 0.71250001  1.19145773  0.7512883  -1.40764393]
 [ 0.11166254 -0.23487621  0.05008688 -0.96848723]]
[5 8 8 8 6 1 6 3]
[[0 1]
 [1 1]
 [9 9]
 [4 4]]
[[0.5218252  0.92448739 0.44380918]
 [0.00296655 0.3487566  0.9901818 ]]


### -------------------------------------

# Pandas

In [4]:
import pandas as pd
import numpy as np

In [35]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4), 
                  index = ['Row1', 'Row2', 'Row3', 'Row4', 'Row5'],
                  columns = ['Col1', 'Col2', 'Col3', 'Col4'])
print(df.head())

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19


In [36]:
# Writing a dataframe to csv file
df.to_csv('Test.csv')

In [50]:
# Accessing the elements
# 1 - .loc ->  label-based indexing, need to specify row and column labels. 
# Syntax - df.loc[row_label, column_label]
print(df.loc['Row1']) # print a row with all the columns
print(df.loc[:,'Col2']) # specifying the rows is necesary, here all rows of Col will be printed
print(df.loc['Row3':'Row5','Col2':'Col4'])
# 2 - .iloc -> integer-based indexing.
# Syntax - df.iloc[row_index, column_index]
df.iloc[:1,2:]
# When slicing a df, the result is a series if there is one column. If there is more than 1 column it is a df

print("accessing a column\n",df['Col1'])

Col1    0
Col2    1
Col3    2
Col4    3
Name: Row1, dtype: int32
Row1     1
Row2     5
Row3     9
Row4    13
Row5    17
Name: Col2, dtype: int32
      Col2  Col3  Col4
Row3     9    10    11
Row4    13    14    15
Row5    17    18    19
accessing a column
 Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Col1, dtype: int32


In [46]:
# Converting a df into an array
print(df.loc['Row3':'Row5','Col2':'Col4'].values) # the .values converts a df to an array
print(df.loc['Row3':'Row5','Col2':'Col4'].values.shape) # shape of the array


[[ 9 10 11]
 [13 14 15]
 [17 18 19]]
(3, 3)


In [47]:
# Functions for a dataframe
print(df.isnull().sum()) # checks for NULL values
print(df['Col1'].value_counts()) # count the occurrences of each unique value in a Series
print(df['Col1'].unique()) # displays unique values in a series
print(df['Col1'].nunique()) # count the number of unique values in a Series

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64


### Reading CSV files

In [51]:
df = pd.read_csv('mercedesbenz.csv')
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [52]:
# Get details about index,non-null values,the number of rows and columns, data types, and missing values.
# It does not provide statistical information about the data within the DataFrame.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [53]:
# generates descriptive statistics of numerical columns in the DataFrame, such as count, mean, std dev, min, max, and quartile values.
# It provides statistical insights into the central tendency, dispersion, and shape of the distribution of numerical data.
# It ignores non-numeric columns and does not provide information about categorical or textual data.
df.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [54]:
# Reading specific columns from a csv; usecols parameter
df = pd.read_csv('Test.csv', usecols=lambda x: x.upper() in ['COL2','COL3'])
print(df)
df.to_csv('Test2.csv')

   Col2  Col3
0     1     2
1     5     6
2     9    10
3    13    14
4    17    18


In [1]:
from io import StringIO, BytesIO

In [2]:
# Storing comma separated values as String
data = ('col1,col2,col3\n'
        'x,y,1\n'
        'a,b,2\n'
        'c,d,3\n')
print(data)
print(type(data))

col1,col2,col3
x,y,1
a,b,2
c,d,3

<class 'str'>


In [5]:
# Reading the comma separated values stored as string in a df
str_df = pd.read_csv(StringIO(data))
print(str_df)
print(type(str_df))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3
<class 'pandas.core.frame.DataFrame'>


In [6]:
# Specifying data types when using read_csv
data2 = ('a,b,c,d\n'
       '1,2,3,4\n'
       '5,6,7,8\n'
       '9,10,11,12')
str_df2 = pd.read_csv(StringIO(data2), dtype=object)
print(str_df2.head())

   a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12


In [10]:
# Specifying different data types for each column when using read_csv
str_df3 = pd.read_csv(StringIO(data2), dtype={'b':int, 'c':float, 'a':'Int64'})
str_df3.head()

a   b     c   d
0  1   2   3.0   4
1  5   6   7.0   8
2  9  10  11.0  12

In [12]:
str_df3.dtypes

a      Int64
b      int32
c    float64
d      int64
dtype: object

In [13]:
# Specifying index columns
data4 = ('index,a,b,c\n'
        '4,apple,bat,5.7\n'
        '8,orange,cow,10')
str_df4 = pd.read_csv(StringIO(data4), index_col=0) # pass the column number which is to be the index; 0 for 1st column
# pass False, if there is no index
str_df4

a    b     c
index                   
4       apple  bat   5.7
8      orange  cow  10.0

In [14]:
# Quoting and Escape characters
line_data = 'a,b\n"hello, \\"Bob\\", nice to see you",5'
line_df = pd.read_csv(StringIO(line_data),escapechar='\\')
line_df

a  b
0  hello, "Bob", nice to see you  5

In [16]:
# URL to CSV; also using \t as a separator
str_df5=pd.read_csv('url', sep='\t')
str_df5

In [3]:
# Read JSON
json_data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
json_df = pd.read_json(json_data)
json_df

C:\Users\Vibhanshu\AppData\Local\Temp\ipykernel_7392\424228615.py:3: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  json_df = pd.read_json(json_data)


employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [4]:
# read json using a url
json_df2 = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)
json_df2

0      1     2     3     4    5     6     7     8     9      10    11  \
0     1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04   
1     1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
2     1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
3     1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
4     1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

       12    13  
0    3.92  1065  
1    3.40  1050  
2    3.17  1185  
3    3.45  1480  
4    2.93   735  
..    ...   ...  
173  1.74   740  
174  1.56   750  
175  1.56   835  
176  1.62   840  
177  1.60   560  

[178 rows x 14 columns]

In [5]:
json_df2.to_csv('wine.csv')

In [7]:
json_df2.to_json(orient="index") # creates a JSON object where the index labels of the DataFrame are used as keys, use orient="index" when you want to preserve the index labels or when dealing with hierarchical data

'{"0":{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},"1":{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},"2":{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},"3":{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},"4":{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},"5":{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},"6":{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},"7":{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.3

In [6]:
json_df2.to_json(orient="records") # creates a JSON array where each element is a dictionary representing a row of the DataFrame, use orient="records" when you want a list of records suitable for API responses or external applications.

'[{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.31,"9":1.25,"10":5.05,"11":1.06,"

In [18]:
# !pip install lxml
# !pip install html5lib
# !pip install beautifulsoup4

'conda' is not recognized as an internal or external command,
operable program or batch file.


In [21]:
# Reading HTML
url = 'https://en.wikipedia.org/wiki/Mobile_country_code'
html_df = pd.read_html(url, match='Country', header=0)
print(html_df)

[     Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobi

In [23]:
!pip install openpyxl

   ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
   - -------------------------------------- 10.2/250.0 kB ? eta -:--:--
   ---- ---------------------------------- 30.7/250.0 kB 435.7 kB/s eta 0:00:01
   -------------- ------------------------ 92.2/250.0 kB 751.6 kB/s eta 0:00:01
   ---------------------------------------  245.8/250.0 kB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 250.0/250.0 kB 1.3 MB/s eta 0:00:00


In [24]:
# Reading Excel files
excel_df = pd.read_excel('Excel_Sample.xlsx', sheet_name=0) # by default the first sheet will be read
print(excel_df.head())

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15
